# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-06-20 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='category',
            field=models.CharField(choices=[('eftc', 'education-focused technology company'), ('plp', 'Personal learning platform'), ('u', 'Univerisity')], default='eftc', max_length=20, verbose_name='Provider category'),
        ),
        migrations.AlterField(
            model_name='courseorg',
            name='image',
            field=models.ImageField(upload_to='org/%Y/%m', verbose_name='Logo'),
        ),
    ]
