# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-08 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_remove_courseorg_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='tag',
            field=models.CharField(default='Well-known', max_length=10, verbose_name='organization tag'),
        ),
    ]
