# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-08 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_courseorg_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseorg',
            name='tag',
            field=models.CharField(default='Start', max_length=10, verbose_name='organization tag'),
        ),
    ]
