# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-02 10:22
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(max_length=200, verbose_name='Comments')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Add time')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='Course name')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Course comments',
                'verbose_name_plural': 'Course comments',
            },
        ),
        migrations.CreateModel(
            name='UserAsk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('mobile', models.CharField(max_length=11, verbose_name='Phone number')),
                ('course_name', models.CharField(max_length=50, verbose_name='Course name')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Add time')),
            ],
            options={
                'verbose_name': 'User reference service',
                'verbose_name_plural': 'User reference service',
            },
        ),
        migrations.CreateModel(
            name='UserCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(max_length=200, verbose_name='Comments')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Add time')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='Course name')),
            ],
            options={
                'verbose_name': 'User course',
                'verbose_name_plural': 'User course',
            },
        ),
        migrations.CreateModel(
            name='UserFavorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fav_id', models.IntegerField(default=0, verbose_name='Data ID')),
                ('fav_type', models.IntegerField(choices=[(1, 'Courses'), (2, 'Organization'), (3, 'Teacher')], default=1, verbose_name='Favorite type')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Add time')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='Course name')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User favorite',
                'verbose_name_plural': 'User favorite',
            },
        ),
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(default=0, verbose_name='Receive user')),
                ('message', models.CharField(max_length=200, verbose_name='Message content')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Add time')),
                ('has_read', models.BooleanField(default=False, verbose_name='Has read')),
            ],
            options={
                'verbose_name': 'User Message',
                'verbose_name_plural': 'User Message',
            },
        ),
    ]
