# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-06-27 06:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operation', '0002_remove_userfavorite_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercourse',
            name='comments',
        ),
        migrations.AddField(
            model_name='usercourse',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User name'),
        ),
    ]
