# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-06-27 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_course_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(default='back end', max_length=20, verbose_name='Course category'),
        ),
    ]
