# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-06-27 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='tags',
            field=models.CharField(default='', max_length=10, verbose_name='Course tag'),
        ),
    ]
