# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-06-27 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='tags',
            field=models.CharField(default='', max_length=100, verbose_name='Course tag'),
        ),
    ]
