# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-06-29 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20170627_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='url',
            field=models.CharField(default='', max_length=200, verbose_name='url'),
        ),
    ]
