# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-06-29 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='learn_times',
            field=models.IntegerField(default=0, verbose_name='Learning time(In minutes)'),
        ),
    ]
