# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-06-29 04:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import organization.models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_remove_courseorg_tags'),
        ('courses', '0008_auto_20170629_0325'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(blank=True, null=organization.models.Teacher, on_delete=django.db.models.deletion.CASCADE, to='organization.Teacher', verbose_name='Professor'),
        ),
    ]
