# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-06-29 04:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_course_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher_notice',
            field=models.CharField(default='', max_length=300, verbose_name='Teacher notice'),
        ),
        migrations.AddField(
            model_name='course',
            name='you_need_know',
            field=models.CharField(default='', max_length=300, verbose_name='Course requirement'),
        ),
    ]
