# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-04 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_banner_emailverifyrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'Gentleman'), ('female', 'Lady')], default='female', max_length=10),
        ),
    ]
