# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-06-06 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170604_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_type',
            field=models.CharField(choices=[('register', 'Register'), ('Forget', 'Forget_password')], max_length=20),
        ),
    ]
