# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-06 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20170606_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_type',
            field=models.CharField(choices=[('register', 'Register'), ('Forget', 'Forget_password'), ('update_email', 'Update_email')], max_length=20),
        ),
    ]
